/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.tlsf.idea.lang


class TLSFFileType extends AbstractTLSFFileType {
	public static final TLSFFileType INSTANCE = new TLSFFileType()
	
	new() {
		super(TLSFLanguage.INSTANCE)
	}
}
