/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.tlsf.idea.completion

import com.rainerschuster.tlsf.idea.lang.TLSFLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class TLSFCompletionContributor extends AbstractTLSFCompletionContributor {
	new() {
		this(TLSFLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
