/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.tlsf.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class TLSFIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new TLSFStandaloneSetupIdea().createInjector
	}

}
