/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.tlsf.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class TLSFIdeaModule extends AbstractTLSFIdeaModule {
}
