/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.tlsf


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TLSFStandaloneSetup extends TLSFStandaloneSetupGenerated {

	def static void doSetup() {
		new TLSFStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
