/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.tlsf.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TLSFUiModule extends AbstractTLSFUiModule {
}
